### ISSUE TITLE
[内容建议]

### ISSUE THREAD

**Issue by GermanniePedia** [FeletexGee/HFYZ-Newbie-Handbook#4]
**内容类型**
生活（入学教育）
**添加理由**
2023级（现在的高一年级）有入学考试，但是延续传统，完全不公布成绩与排名（但是因为系统的bug刚开始有一段时间可以查到成绩，后来关闭了查询渠道）；
依照2023级的入学教育情况，开学后走读/半走读的同学无须在入学教育和军训期间住宿，因此也无须携带生活用品（半走读要带被子）；
优芙德今年口碑似乎上升（？），作为高一学生，同级之间评价较好。增加韩式拌饭、锡纸锅烤鱼等新品种。

无论如何，强烈建议你在被采纳之后向Dev branch提交Pull request.

**Comment by FeletexGee** [comment]
好的，收到。感谢你的帮助：-）
（顺便优芙德是我在校期间光顾最多的一家食堂哈哈哈
